on:
  push:
    branches:
      - '**'
  workflow_dispatch:
name: dependabot-build
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  publish:
    uses: nr1etech/github-workflows/.github/workflows/javascript-library.yml@develop
    if: github.actor == 'dependabot[bot]'
    with:
      node-versions: '[22,24]'
    secrets:
      app-id: ${{ secrets.RELEASE_BOT_ID }}
      private-key: ${{ secrets.RELEASE_BOT_KEY }}
